'use client';
import { Inter } from 'next/font/google'
import Head from 'next/head'
import { BsFillMoonStarsFill } from 'react-icons/bs'
import { AiFillFacebook, AiFillLinkedin, AiFillTwitterCircle, AiFillTwitterSquare } from 'react-icons/ai'
import Image from 'next/image'
import ProfilePicture from 'public/raheeldp.jpeg'
import CodeImage from 'public/code.png'
import DesignImage from 'public/design.png'
import ConsultingImage from 'public/consulting.png'
import w1 from 'public/web1.png'
import w2 from 'public/web2.png'
import w3 from 'public/web3.png'
import w4 from 'public/web4.png'
import w5 from 'public/web5.png'
import w6 from 'public/web6.png'
import { useState } from "react";



const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Muhammad Raheel Portfolio</title>
        <meta name="description" content='Generated by Raheel'></meta>
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className=' bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40 dark:text-white'>
        <section className='min-h-screen'>
          <nav className='flex py-10 mb-12 justify-between'>
            <h1 className='text-xl font-burtons'>developedbyraheel</h1>

            <ul className='flex items-center'>
              <li><BsFillMoonStarsFill className='cursor-pointer text-2xl' onClick={() => setDarkMode(!darkMode)} /></li>
              <li><a className='bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8' href="#">Resume</a></li>
            </ul>
          </nav>

          <div className='p-10 text-center'>

            <h2 className='text-5xl text-teal-600 py-2'>Muhammad Raheel</h2>
            <h3 className='text-2xl py-2 text-gray-800 md:text-3xl dark:text-white'>Software Enginner / Frontend Developer</h3>
            <p className='text-md leading-8 max-w-xl mx-auto md:text-xl py-5'>Freelancer providing services for programming and design content needs. Join me down below and let's get cracking!</p>
            <div className='flex text-5xl justify-center gap-16 py-3 text-gray-600 dark:text-white'>
              <AiFillTwitterSquare />
              <AiFillFacebook />
              <AiFillLinkedin />
            </div>
            <div className='mt-20 bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mx-auto overflow-hidden relative md:w-96 md:h-96'>
              <Image src={ProfilePicture} fill style={{ objectFit: "contain" }} alt="Profile Image" />
            </div>

          </div>
        </section>
        <section>
          <div>
            <h3 className='text-3xl py-1'>Services I offer</h3>
            <p className='text-md leading-8 text-gray-800 py-2 dark:text-white'>Since the beginning of my journey as a freelance designer and developer, I've done remote work for <span className='text-teal-500'>agencies</span> consulted for <span className='text-teal-500'>startups</span> and collaborated with talanted people to create digital products for both business and consumer use.</p>
            <p className='text-md leading-8 text-gray-800 py-2 dark:text-white'>I offer from a wide range of services, including brand design, programming and teaching.</p>
          </div>

          <div className='lg:flex gap-10'>
            <div className='p-10 text-center shadow-lg border border-gray-50 rounded-xl my-10 flex-1 dark:bg-white'>
              <Image alt='code' style={{ margin: 'auto' }} src={DesignImage} width={100} height={100} />
              <h3 className='text-lg font-medium mt-10 mb-2 dark:text-gray-900'>Beautiful Designs</h3>
              <p className='py-2 text-gray-800'>Creating elegant designs suited for your needs following core design theory.</p>
              <h3 className='py-4 text-teal-600'>Design Tools I Use</h3>
             
              <p className='py-1 text-gray-800'>Photoshop</p>
              <p className='py-1 text-gray-800'>Illustrator</p>
              <p className='py-1 text-gray-800'>Figma</p>
              <p className='py-1 text-gray-800'>InDesign</p>
              
            </div>

            <div className='p-10 text-center shadow-lg border border-gray-50 rounded-xl my-10 flex-1 dark:bg-white'>
              <Image alt='code' style={{ margin: 'auto' }} src={CodeImage} width={100} height={100} />
              <h3 className='text-lg font-medium mt-10 mb-2 dark:text-gray-900'>Code your dream project</h3>
              <p className='py-2 text-gray-800'>Do you have an idea for your next great website? Let's make it a reality.</p>
              <h3 className='py-4 text-teal-600'>Design Tools I Use</h3>
             
              <p className='py-1 text-gray-800'>Photoshop</p>
              <p className='py-1 text-gray-800'>Illustrator</p>
              <p className='py-1 text-gray-800'>Figma</p>
              <p className='py-1 text-gray-800'>InDesign</p>

            </div>

            <div className='p-10 text-center shadow-lg border border-gray-50 rounded-xl my-10 flex-1 dark:bg-white'>
              <Image alt='code' style={{ margin: 'auto' }} src={ConsultingImage} width={100} height={100} />
              <h3 className='text-lg font-medium mt-10 mb-2 dark:text-gray-900'>Consulting</h3>
              <p className='py-2 text-gray-800'>Are you interested in feedback for your current project? I can give you tips and tricks to level it up.</p>
              <h3 className='py-4 text-teal-600'>Design Tools I Use</h3>
             
              <p className='py-1 '>Photoshop</p>
              <p className='py-1 text-gray-800'>Illustrator</p>
              <p className='py-1 text-gray-800'>Figma</p>
              <p className='py-1 text-gray-800'>InDesign</p>
            </div>

          </div>

        </section>

        <section>
          <h3 className='text-3xl py-1'>Portfolio</h3>
          <p className='text-md leading-8 py-2'>Since the beginning of my journey as a freelance designer and developer, I've done remote work for <span className='text-teal-500'>agencies</span> consulted for <span className='text-teal-500'>startups</span> and collaborated with talanted people to create digital products for both business and consumer use.</p>
          <p className='text-md leading-8 py-2'>I offer from a wide range of services, including brand design, programming and teaching.</p>
        
          <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
            <div className='basis-1/4 flex-1'>
              <Image className='rounded-lg h-full w-full' style={{ objectFit: "cover" }} alt='project-snap-1' src={w1} />
            </div>
            <div className='basis-1/4 flex-1'>
              <Image className='rounded-lg h-full w-full' style={{ objectFit: "cover" }} alt='project-snap-1' src={w2} />
            </div>
            <div className='basis-1/4 flex-1'>
              <Image className='rounded-lg h-full w-full' style={{ objectFit: "cover" }} alt='project-snap-1' src={w3} />
            </div>
            <div className='basis-1/4 flex-1'>
              <Image className='rounded-lg h-full w-full' style={{ objectFit: "cover" }} alt='project-snap-1' src={w4} />
            </div>
            <div className='basis-1/4 flex-1'>
              <Image className='rounded-lg h-full w-full' style={{ objectFit: "cover" }} alt='project-snap-1' src={w5} />
            </div>
            <div className='basis-1/4 flex-1'>
              <Image className='rounded-lg h-full w-full' style={{ objectFit: "cover" }} alt='project-snap-6' src={w6} />
            </div>
            
          </div>
        </section>
      </main>
    </div>
  )
}
